Models/WISHLIST.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wanderlust.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WISHLIST
    {
        public int item_id { get; set; }
        public int dest_id { get; set; }
        public int user_id { get; set; }
    
        public virtual DESTINATION DESTINATION { get; set; }
        public virtual USER USER { get; set; }
    }
}

Controllers/WishlistController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Wanderlust.Models;

namespace Wanderlust.Controllers
{
    public class WishlistController : Controller
    {
        private WanderlustEntities db = new WanderlustEntities();


        public ActionResult Index()
        {

            if (Session["UserId"] == null)
            {
                TempData["ErrorMessage"] = "Please login to view your wishlist.";
                return RedirectToAction("Login", "Account");
            }

            int userId = Convert.ToInt32(Session["UserId"]);


            var userWishlist = db.WISHLISTs
                .Include(w => w.DESTINATION)
                .Where(w => w.user_id == userId)
                .ToList();

            return View(userWishlist);
        }

        // GET: Wishlist/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WISHLIST wISHLIST = db.WISHLISTs.Find(id);
            if (wISHLIST == null)
            {
                return HttpNotFound();
            }
            return View(wISHLIST);
        }

        // GET: Wishlist/Create
        // GET: Wishlist/AddToWishlist/5
        public ActionResult AddToWishlist(int id)
        {
            if (Session["UserId"] == null)
            {
                TempData["ErrorMessage"] = "Please login to add items to your wishlist.";
                return RedirectToAction("Login", "Account");
            }

            int userId = Convert.ToInt32(Session["UserId"]);

            // Check if this destination is already in the user's wishlist
            var existingWishlist = db.WISHLISTs.FirstOrDefault(w => w.dest_id == id && w.user_id == userId);

            if (existingWishlist == null)
            {
                // Create new wishlist item
                var wishlist = new WISHLIST
                {
                    dest_id = id,
                    user_id = userId
                };

                db.WISHLISTs.Add(wishlist);
                db.SaveChanges();

                TempData["SuccessMessage"] = "Added to Wishlist!";
            }
            else
            {
                TempData["InfoMessage"] = "This item is already in your wishlist.";
            }

            // Return to the previous page
            return Redirect(Request.UrlReferrer.ToString());
        }



        // GET: Wishlist/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WISHLIST wISHLIST = db.WISHLISTs.Find(id);
            if (wISHLIST == null)
            {
                return HttpNotFound();
            }
            return View(wISHLIST);
        }

        // POST: Wishlist/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WISHLIST wISHLIST = db.WISHLISTs.Find(id);
            db.WISHLISTs.Remove(wISHLIST);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Wishlist/Create.cshtml
@model Wanderlust.Models.WISHLIST

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>WISHLIST</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.dest_id, "dest_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("dest_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.dest_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user_id, "user_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("user_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Wishlist/Edit.cshtml
@model Wanderlust.Models.WISHLIST

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WISHLIST</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.item_id)

        <div class="form-group">
            @Html.LabelFor(model => model.dest_id, "dest_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("dest_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.dest_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.user_id, "user_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("user_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.user_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Wishlist/Index.cshtml
@model IEnumerable<Wanderlust.Models.WISHLIST>
@{
    ViewBag.Title = "My Wishlist";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container my-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 style="color: #ff7f50;"><i class="bi bi-heart-fill text-danger me-2"></i>My Wishlist</h2>
    </div>

    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            @TempData["SuccessMessage"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }

    @if (!Model.Any())
    {
        <div class="alert alert-info">
            <p class="mb-0">Your wishlist is empty. Browse our <a href="@Url.Action("Index", "Destination")" class="alert-link">destinations</a> to add some!</p>
        </div>
    }
    else
    {
        <div class="row g-4">
            @foreach (var item in Model)
            {
                <div class="col-md-6 col-lg-4">
                    <div class="card h-100 shadow border-0" style="background-color: #fff5f0;">
                        <div class="position-relative">
                            <img src="~/@item.DESTINATION.image" class="card-img-top" alt="@item.DESTINATION.destName"
                                 style="height: 200px; object-fit: cover; border-top-left-radius: 0.5rem; border-top-right-radius: 0.5rem;">
                            <div class="position-absolute top-0 end-0 p-2">
                                @using (Html.BeginForm("Delete", "Wishlist", new { id = item.item_id }, FormMethod.Post, new { @class = "d-inline" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <button type="submit" class="btn btn-danger btn-sm"
                                            onclick="return confirm('Are you sure you want to remove this from your wishlist?');">
                                        <i class="bi bi-trash"></i>
                                    </button>
                                }
                            </div>
                        </div>

                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title text-center" style="color: #d2691e;">@item.DESTINATION.destName</h5>

                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <span class="badge bg-info">$@item.DESTINATION.price</span>

                            </div>

                            <p class="card-text flex-grow-1">
                                @(item.DESTINATION.description != null && item.DESTINATION.description.Length > 100
                                    ? item.DESTINATION.description.Substring(0, 100) + "..."
                                    : item.DESTINATION.description)
                            </p>

                            <div class="d-grid gap-2">
                                <a href="@Url.Action("Details", "Destination", new { id = item.dest_id })" class="btn btn-autumn">
                                    <i class="bi bi-eye me-1"></i> View Details
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
</div>